package com.example.data.newpipe.mapper.video

import com.example.data.newpipe.mapper.base.BaseMapper
import com.example.domain.model.youtube.channel.ChannelTabResult
import com.example.domain.model.youtube.search.SearchResult
import com.example.domain.model.youtube.video.Video
import com.example.domain.model.youtube.video_detail.SubtitleTrack
import com.example.domain.model.youtube.video_detail.VideoDetail
import com.example.util.Logger
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.StreamExtractor
import org.schabi.newpipe.extractor.stream.StreamInfoItem

object VideoMapper {

    fun streamInfoItemToSearchResultVideo(
        item: StreamInfoItem,
        videoId: String,
        uploaderId: String
    ): SearchResult.VideoResult {
        return SearchResult.VideoResult(
            video = streamInfoItemToBasicVideoData(item, videoId, uploaderId)
        )
    }

    fun streamInfoItemToChannelTabResultVideo(
        item: StreamInfoItem,
        videoId: String,
        uploaderId: String
    ): ChannelTabResult.VideoResult {
        return ChannelTabResult.VideoResult(
            video = streamInfoItemToBasicVideoData(item, videoId, uploaderId)
        )
    }

    fun streamInfoItemToChannelTabResultShorts(
        item: StreamInfoItem,
        videoId: String,
        uploaderId: String
    ): ChannelTabResult.ShortsResult {
        return ChannelTabResult.ShortsResult(
            video = streamInfoItemToBasicVideoData(item, videoId, uploaderId)
        )
    }

    fun streamInfoItemToBasicVideoData(
        item: StreamInfoItem,
        videoId: String,
        uploaderId: String
    ): Video {
        return Video(
            id = videoId,
            title = item.name,
            description = item.shortDescription ?: "",
            publishTimestamp = item.uploadDate?.offsetDateTime()?.toInstant()?.toEpochMilli(),
            thumbnailUrl = BaseMapper.getHighestResThumbnail(item.thumbnails.firstOrNull()?.url),
            infoType = "Stream",
            uploaderName = item.uploaderName,
            uploaderUrl = uploaderId,
            uploaderAvatarUrl = item.uploaderAvatars.firstOrNull()?.url,
            uploaderVerified = item.isUploaderVerified,
            duration = item.duration,
            viewCount = item.viewCount,
            textualUploadDate = item.textualUploadDate,
            streamType = item.streamType?.name,
            shortFormContent = item.isShortFormContent
        )
    }

    fun streamExtractorToVideoDetail(
        extractor: StreamExtractor,
        uploaderId: String,
        video: Video
    ): VideoDetail {
        val videoStreams = extractor.videoStreams
        val videoOnlyUrls = extractor.videoOnlyStreams.toList()
        val audioOnlyUrls = extractor.audioStreams.toList()
        val subtitleTracks = runCatching {
            extractor.getSubtitles(MediaFormat.VTT)
                .mapNotNull { subtitle ->
                    val content = subtitle.getContent()
                    if (!subtitle.isUrl() || content.isBlank()) {
                        null
                    } else {
                        SubtitleTrack(
                            url = content,
                            languageTag = subtitle.getLanguageTag(),
                            autoGenerated = subtitle.isAutoGenerated(),
                        )
                    }
                }
        }.getOrDefault(emptyList())

        Logger.d("VideoMapper HLS URL: ${extractor.hlsUrl}")

        return VideoDetail(
            id = extractor.id,
            title = extractor.name,
            videoStreams = videoStreams,
            videoStreamContent = videoStreams.firstOrNull()?.content,
            videoOnlyStreams = videoOnlyUrls,
            audioOnlyStreams = audioOnlyUrls,
            duration = video.duration,
            description = extractor.description.content,
            thumbnailUrl = BaseMapper.getHighestResThumbnail(extractor.thumbnails.firstOrNull()?.url),
            uploaderName = extractor.uploaderName,
            uploaderId = uploaderId,
            uploaderAvatarUrl = extractor.uploaderAvatars.firstOrNull()?.url,
            uploaderSubscriberCount = extractor.uploaderSubscriberCount,
            publishTimestamp = extractor.uploadDate?.offsetDateTime()?.toInstant()?.toEpochMilli(),
            publishedTimeText = extractor.textualUploadDate,
            viewCount = extractor.viewCount,
            likeCount = extractor.likeCount,
            dislikeCount = extractor.dislikeCount,
            relatedVideos = extractor.relatedItems?.items?.mapNotNull {
                val relatedVideo = it as? StreamInfoItem ?: return@mapNotNull null
                val videoId = try {
                    ServiceList.YouTube.streamLHFactory.getId(relatedVideo.url)
                } catch (e: Exception) {
                    Logger.d("VideoMapper", "Failed to extract video ID from URL: ${relatedVideo.url}")
                    return@mapNotNull null
                }
                val relatedUploaderId = try {
                    ServiceList.YouTube.channelLHFactory.getId(relatedVideo.uploaderUrl)
                        .replace("channel/", "")
                } catch (e: Exception) {
                    ""
                }
                Video(
                    id = videoId,
                    title = relatedVideo.name,
                    description = relatedVideo.shortDescription ?: "",
                    publishTimestamp = relatedVideo.uploadDate?.offsetDateTime()?.toInstant()?.toEpochMilli(),
                    thumbnailUrl = BaseMapper.getHighestResThumbnail(relatedVideo.thumbnails.firstOrNull()?.url),
                    infoType = "Stream",
                    uploaderName = relatedVideo.uploaderName,
                    uploaderUrl = relatedUploaderId,
                    uploaderAvatarUrl = relatedVideo.uploaderAvatars.firstOrNull()?.url,
                    uploaderVerified = relatedVideo.isUploaderVerified,
                    duration = relatedVideo.duration,
                    viewCount = relatedVideo.viewCount,
                    textualUploadDate = relatedVideo.textualUploadDate ?: "",
                    streamType = relatedVideo.streamType?.name,
                    shortFormContent = relatedVideo.isShortFormContent
                )
            } ?: emptyList(),
            subtitleTracks = subtitleTracks,
        )
    }
}
